"""miner fix on ask model

Revision ID: 183b06b9c722
Revises: f57206891beb
Create Date: 2023-08-03 09:04:04.585184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '183b06b9c722'
down_revision = 'f57206891beb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
