"""added telegram options for user

Revision ID: 1e8e9e1f2a15
Revises: f34f32debea6
Create Date: 2023-08-02 11:44:21.608148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e8e9e1f2a15'
down_revision = 'f34f32debea6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telegram_id', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('firstname', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=False))
    op.drop_column('user', 'fullname')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('fullname', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('user', 'username')
    op.drop_column('user', 'firstname')
    op.drop_column('user', 'telegram_id')
    # ### end Alembic commands ###
