"""fixed prompt spelling

Revision ID: 29ae4356a08c
Revises: 9121f8a212c2
Create Date: 2023-08-08 08:53:53.526936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ae4356a08c'
down_revision = '9121f8a212c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('system_prompt', sa.String(length=5000), nullable=False))
    op.drop_column('conversation', 'system_propmpt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation', sa.Column('system_propmpt', sa.VARCHAR(length=5000), autoincrement=False, nullable=False))
    op.drop_column('conversation', 'system_prompt')
    # ### end Alembic commands ###
