"""removed all the columns that are going to store Q/A

Revision ID: 3f6519922a98
Revises: fa9bd44b0b44
Create Date: 2023-08-08 13:19:12.668426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6519922a98'
down_revision = 'fa9bd44b0b44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ask', 'answer')
    op.drop_column('ask', 'question')
    op.drop_column('conversation', 'system_prompt')
    op.drop_column('message', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('content', sa.VARCHAR(length=5000), autoincrement=False, nullable=False))
    op.add_column('conversation', sa.Column('system_prompt', sa.VARCHAR(length=5000), autoincrement=False, nullable=False))
    op.add_column('ask', sa.Column('question', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.add_column('ask', sa.Column('answer', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
