"""first commit

Revision ID: 51883a385253
Revises: ddf696ca2dee
Create Date: 2023-07-20 15:53:19.217971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51883a385253'
down_revision = 'ddf696ca2dee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fullname')
    op.drop_column('user', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('fullname', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
