"""removed ask model

Revision ID: 5eb8be083ce4
Revises: 7fe27075abed
Create Date: 2023-08-03 09:22:09.231863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb8be083ce4'
down_revision = '7fe27075abed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ask')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ask',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('answer', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='ask_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ask_pkey')
    )
    # ### end Alembic commands ###
