"""fix

Revision ID: 7fe27075abed
Revises: 9a411a2a64e2
Create Date: 2023-08-03 09:14:12.046857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe27075abed'
down_revision = '9a411a2a64e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
