"""added conversation and messages

Revision ID: 9121f8a212c2
Revises: 67b90d0e6c2d
Create Date: 2023-08-08 08:29:37.943255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9121f8a212c2'
down_revision = '67b90d0e6c2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('persona', sa.String(length=50), nullable=False),
    sa.Column('system_propmpt', sa.String(length=5000), nullable=False),
    sa.Column('total_token', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(length=5000), nullable=False),
    sa.Column('token_usage', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('conversation')
    # ### end Alembic commands ###
