"""add ask model

Revision ID: 95019d68effe
Revises: 5eb8be083ce4
Create Date: 2023-08-03 09:24:29.484634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95019d68effe'
down_revision = '5eb8be083ce4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
