"""increased the size of varchar for all the fields that have string field

Revision ID: a6d7a39842d5
Revises: 3f6519922a98
Create Date: 2023-08-08 13:21:06.646885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d7a39842d5'
down_revision = '3f6519922a98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ask', sa.Column('question', sa.String(length=100000), nullable=False))
    op.add_column('ask', sa.Column('answer', sa.String(length=100000), nullable=False))
    op.add_column('conversation', sa.Column('system_prompt', sa.String(length=100000), nullable=False))
    op.add_column('message', sa.Column('content', sa.String(length=100000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'content')
    op.drop_column('conversation', 'system_prompt')
    op.drop_column('ask', 'answer')
    op.drop_column('ask', 'question')
    # ### end Alembic commands ###
