"""remove test

Revision ID: c72e660b696b
Revises: 3861f6f903c2
Create Date: 2023-07-23 13:24:08.493364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72e660b696b'
down_revision = '3861f6f903c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test', sa.VARCHAR(), server_default=sa.text("'mapped str is str'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
