"""first commit

Revision ID: ddf696ca2dee
Revises: fcf679dfd861
Create Date: 2023-07-20 15:48:05.749955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf696ca2dee'
down_revision = 'fcf679dfd861'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###
