"""remove test

Revision ID: f34f32debea6
Revises: c72e660b696b
Create Date: 2023-07-23 13:25:55.469988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34f32debea6'
down_revision = 'c72e660b696b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('age', sa.INTEGER(), server_default=sa.text('20'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
