"""miner fix on ask model

Revision ID: f57206891beb
Revises: 199c477f3ae0
Create Date: 2023-08-03 09:00:12.562788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57206891beb'
down_revision = '199c477f3ae0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
