"""increase word length

Revision ID: fa9bd44b0b44
Revises: 3e2d933fa0e9
Create Date: 2023-08-08 13:15:18.808290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9bd44b0b44'
down_revision = '3e2d933fa0e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
